#!/bin/bash

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/encompass/Encompass-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/encompass/deterministic.spec"
cp /opt/wine-electrum/drive_c/encompass/encompass.nsi $SOURCEDIR/

echo "Running c:/encompass/Encompass-$VERSION/encompass.nsi for install"
xvfb-run wine c:\\"Program Files"\\NSIS\\makensis.exe -V1 c:/encompass/Encompass-$VERSION/encompass.nsi


cleanup
