#!/usr/bin/python

from lib.version import ELECTRUM_VERSION as version

if __name__ == '__main__':
    import sys, re, shutil, os, hashlib

    if not ( os.path.exists('packages')):
        print "The packages directory is missing."
        os.mkdir('packages')

    # os.system("python mki18n.py")
    os.system("pyrcc4 icons.qrc -o gui/qt/icons_rc.py")
    os.system("python setup.py sdist --format=zip,gztar")
    
    _tgz="Encompass-%s.tar.gz"%version
    _zip="Encompass-%s.zip"%version

    # Load modules into zip and tar for release building
    os.mkdir("tmp")
    ##os.system("pip install --pre --no-compile -t tmp slowaes")
    os.system("pip install --no-compile -t tmp 'ecdsa==0.13' ")
    os.system("pip install --no-compile -t tmp 'pyasn1_modules==0.0.5'")
    os.system("pip install --no-compile -t tmp 'pyasn1==0.1.7'")
    os.system("pip install --no-compile -t tmp 'qrcode==5.1' ")
    os.system("pip install --no-compile -t tmp 'requests==2.5.1' ")
    os.system("pip install --no-compile -t tmp 'tlslite==0.4.8'")
    # these modules are just files rather than directories
    os.mkdir("tmp/lib")
    os.system("pip install --pre --no-compile -t tmp/lib 'slowaes<=0.1a1'")
    os.system("pip install --no-compile -t tmp/lib 'pbkdf2<=1.3'")
    os.system("pip install --no-compile -t tmp/lib 'SocksiPy-branch<=1.01'")
    # load modules into archive
    os.system("mv tmp dist/Encompass-%s"%version)
    os.chdir("dist")
    os.system("zip -r %s Encompass-%s"%(_zip, version))
    os.chdir("..")
    os.system("rm -rf dist/Encompass-%s"%version)


    # android
    os.system('rm -rf dist/t4a-%s'%version)
    os.mkdir('dist/t4a-%s'%version)
    shutil.copyfile("encompass",'dist/t4a-%s/t4a.py'%version)
    shutil.copytree("packages",'dist/t4a-%s/packages'%version)
    shutil.copytree("lib",'dist/t4a-%s/lib'%version)
    os.mkdir('dist/t4a-%s/gui'%version)
    for n in ['android.py']:
        shutil.copy("gui/%s"%n,'dist/t4a-%s/gui'%version)
    open('dist/t4a-%s/gui/__init__.py'%version,'w').close()

    os.chdir("dist")
    # create the zip file
    os.system( "zip -r t4a-%s.zip t4a-%s"%(version, version) )
    os.system( "rm -rf t4a-%s"%(version) )

    # change filename because some 3G carriers do not allow users to download a zip file...
    e4a_name = "t4a-%s.zip"%version
    e4a_name2 = e4a_name.replace(".","")
    os.system( "mv %s %s"%(e4a_name, e4a_name2) )

    md5_tgz = hashlib.md5(file(_tgz, 'r').read()).digest().encode('hex')
    md5_zip = hashlib.md5(file(_zip, 'r').read()).digest().encode('hex')
    md5_android = hashlib.md5(file(e4a_name2, 'r').read()).digest().encode('hex')
    os.chdir("..")

    print ""
    print "Packages are ready:"
    print "dist/%s     "%_tgz, md5_tgz
    print "dist/%s        "%_zip, md5_zip
    print "dist/%s                "%e4a_name2, md5_android
    print "To make a release, upload the files to the server, and update the webpages in branch gh-pages"

