#!/bin/bash 
set -xeo pipefail

VERSION="${1}"
test -z ${VERSION} && exit 1 

test -d /root/encompass-release/helpers/release-packages/Linux \
 && rm -rf /root/encompass-release/helpers/release-packages/Linux
cd /root/repo
rm -rf build dist packages
find ./ -name '*.pyc' | xargs rm
mkdir packages
pip install --upgrade --target packages -r ../requirements.txt
cp  /root/encompass-release/python-trezor/trezorctl packages/trezorctl.py
cp -av /root/packages/google/__init__.py /root/repo/packages/google
cp /root/encompass-release/source/linux.spec /root/repo
su build -c 'pyinstaller --windowed linux.spec'
cd dist
mv encompass Encompass-"${VERSION}"
#put installer script in here
tar -cpzvf Encompass-"${VERSION}"_Linux-x86_64.tgz Encompass-"${VERSION}"
mkdir /root/encompass-release/helpers/release-packages/Linux
mv Encompass-"${VERSION}"_Linux-x86_64.tgz /root/encompass-release/helpers/release-packages/Linux
