#!/bin/bash
set -xeo pipefail
###########
## work in progress
## makes installable deb file
## plus self-installer. 
## doesn't fully install deps
##
VERSION="$1"

apt-get install -y python-pip python-all debhelper
pip install stdeb
mkdir -pv /root/encompass-release/ltc_scrypt-1.0/debian_package/ltc_scrypt-1.0
mkdir -pv /root/encompass-release/darkcoin_hash-1.1/debian_package/darkcoin_hash-1.1
mkdir -pv /root/repo/debian_package/Encompass-${VERSION}
cd /root/encompass-release
wget https://pypi.python.org/packages/source/S/SocksiPy-branch/SocksiPy-branch-1.01.tar.gz
tar -xpzvf SocksiPy-branch-1.01.tar.gz

build_module (){
 MODULE="${1}"
 MODDIR="${2}"
 cd /root/encompass-release
 cp /root/setup.py-${MODULE} ${MODULE}/setup.py
 tar -cpzvf ${MODULE}.tar.gz ${MODULE} 
 mv ${MODULE}.tar.gz ${MODULE}
 cd ${MODULE}
 py2dsc ${MODULE}.tar.gz
 echo $(pwd)
 cd deb_dist/${MODDIR}
 dpkg-buildpackage -rfakeroot -uc -us
 cd ..
 cp python-* /root/repo/debian_package/Encompass-${VERSION}
}



build_module ltc_scrypt-1.0 ltc-scrypt-1.0
build_module darkcoin_hash-1.1 darkcoin-hash-1.1
build_module SocksiPy-branch-1.01 SocksiPy-branch-1.01
cd /root/repo
python setup.py --command-packages=stdeb.command bdist_deb
cp deb_dist/python-* /root/repo/debian_package/Encompass-${VERSION}
cd ..
cd /root/repo/debian_package
cp -av /root/requirements.txt /root/repo/debian_package/Encompass-${VERSION}
tar -cpzvf encompass-${VERSION}_ubuntu.tar.gz Encompass-${VERSION}

sed -e 's/ELECTRUM_VERSION/'${VERSION}'/g' /root/debian_installer.in > /root/debian_installer.sh
cat /root/debian_installer.sh encompass-${VERSION}_ubuntu.tar.gz  > encompass-${VERSION}_ubuntu
chmod +x encompass-${VERSION}_ubuntu
test -d /root/release-packages/Ubuntu || mkdir -pv /root/release-packages/Ubuntu
cp -av /root/repo/debian_package/Encompass-${VERSION} /root/release-packages/Ubuntu 
mv /root/repo/debian_package/encompass-${VERSION}_ubuntu.tar.gz  /root/release-packages/Ubuntu
mv /root/repo/debian_package/encompass-${VERSION}_ubuntu  /root/release-packages/Ubuntu
